# Generated by Django 4.1.2 on 2022-10-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_photo"),
    ]

    operations = [
        migrations.DeleteModel(name="Photo",),
    ]
